properties:
  dummy_files_path: C:\Users\Anupama\IdeaProjects\CompressionLibraryBenchmarking\src\main\resources\dummy_files\
  output_folder_path: C:\Users\Anupama\IdeaProjects\CompressionLibraryBenchmarking\src\main\resources\output\